<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- General Project Information -->
        <AssemblyName>MaxWasUnavailable.Nuclei.Adapters</AssemblyName>
        <PackageId>MaxWasUnavailable.Nuclei.Adapters</PackageId>
        <Title>Nuclei.Adapters</Title>
        <Description>Game-specific adapters and lookup utilities for Nuclei.</Description>
        <Version>1.0.0</Version>
        <Authors>MaxWasUnavailable</Authors>
        <PackageTags>nuclear;option;bepinex</PackageTags>

        <!-- Package Information -->
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/MaxWasUnavailable/Nuclei</PackageProjectUrl>
        <RepositoryUrl>https://github.com/MaxWasUnavailable/Nuclei</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Nuclei.Abstractions\Nuclei.Abstractions.csproj" />
    </ItemGroup>

    <!-- Nuclear Option-specific Assembly References -->
    <Import Project="..\build\GameReferences.props" />
</Project>
